name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [7, 9, 10]

        include:
          - os: ubuntu-latest
            node_version: 9
            is_ubuntu_9: "true"

        exclude:
          - os: ubuntu-latest
            node_version: 7
          - os: macos-latest
            node_version: 9

    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_9}}
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node node-version
        run: |
          node -v
          echo $IS_UBUNTU_8

